const icon = name => `<img src="assets/${name}.svg" alt="">`;
const orders = [
  {id:'87654321',services:[{status:'progress',statusText:'В работе',service:'327632724',creator:'Маша Петрова',company:'ООО «Компания Отели Онлайн»',contractor:'ООО «АКАДЕМ-ОНЛАЙН»',created:'1 дек 2026',stay:'20 дек чт – 21 дек 2026 пт',hotel:'Услуги размещения в «Шато»',address:'Россия, Махачкала, ул. Магомедтагирова 2, корпус 2Б',room:'Люкс с 2 односпальными кроватями',meal:'Завтрак включён',mealText:'«Шведский стол» для 2 чел.',guests:'Таранов Александр, Россия',price:'5 936 ₽',points:'350,22 ₽',tax:'НДС не облагается',benefit:'Доп. выгода 150,22 ₽'}]},
  {id:'87654322',services:[{status:'confirmed',statusText:'Подтверждена',service:'327632727',creator:'Светлана Смирнова',company:'ООО «АОН.РУ»',contractor:'ООО «АОН.РУ»',created:'18 мая 2026',stay:'20 дек чт – 21 дек 2026 пт',hotel:'Услуги размещения в «Андреевский»',address:'Россия, Москва, улица Павла Андреева, 4',room:'Стандарт с 2 односпальными кроватями',meal:'Доп питание',mealText:'ужин «Континентальный» для 2 чел.',guests:'Иванов Иван, Россия · Владислава Петрова, Армения',price:'45 500 ₽',points:'240 ₽',tax:'НДС не облагается',benefit:'Доп. выгода 120 ₽'},{status:'registered',statusText:'Зарегистрирован',service:'327632729',creator:'Смирный Антон',company:'ООО «АОН.РУ»',contractor:'ООО «АОН.РУ»',created:'1 дек 2026',stay:'19 ноя чт – 21 дек 2026 пт',hotel:'Услуги размещения в «Буше»',address:'Россия, Москва, ул. Макаренко, 2/21с1',room:'Комфорт с 1 односпальной кроватью',meal:'Завтрак включён',mealText:'«Шведский стол» для 1 чел.',guests:'Сучкова Екатерина, Россия',price:'11 532 ₽',points:'150 ₽',tax:'НДС 100 ₽',benefit:'Доп. выгода 50 ₽'}]}
];
function details(s){return `<div class="details"><div class="detail">${icon('map-pin')}<b class="heading-regular">${s.hotel}</b><span>${s.address}</span></div><div class="detail">${icon('room')}<b class="heading-regular">1 номер</b><span>${s.room}</span></div><div class="detail">${icon('calendar')}<b>Заезд и выезд</b><span>после 14:00 2 авг, до 12:00 4 авг 2026</span></div><div class="detail">${icon('breakfast')}<b>${s.meal}</b><span>${s.mealText}</span></div><div class="detail">${icon('people')}<b>Гости</b><span>${s.guests}</span></div><div class="detail">${icon('payment')}<b>Штрафные санкции</b><span>с 14:00 20 авг 2026 – 100% от полной стоимости в размере 9 000 ₽<br>По местному времени объекта проживания</span></div></div>`}
function voucher(s){if(s.status!=='registered')return '';return `<div class="voucher"><button class="voucher__button" type="button" aria-expanded="false"><svg viewBox="0 0 14 13" aria-hidden="true"><path d="M14 7.5v3.03c0 .952-.647 1.756-1.575 1.955C11.328 12.72 9.498 13 7 13s-4.33-.28-5.425-.515A1.995 1.995 0 0 1 0 10.53V7.5h1.5v3.03c0 .238.16.439.389.488C2.914 11.238 4.632 11.5 7 11.5s4.085-.262 5.11-.481a.498.498 0 0 0 .39-.488V7.5H14ZM11 5 9.939 3.939 7.75 6.129V0h-1.5v6.129L4.061 3.939 3 5l4 4 4-4Z"/></svg><span>Ваучер</span></button><div class="voucher__menu" role="dialog" aria-label="Выбор ваучеров"><div class="voucher__title">Все ваучеры</div><div class="voucher__options"><label><input type="checkbox">С питанием</label><label><input type="checkbox" checked>Без питания</label><label><input type="checkbox">Со штрафами</label><label><input type="checkbox" checked>Без штрафов</label></div><button class="voucher__download" type="button">Скачать</button></div></div>`}
function service(s){return `<div class="service"><div class="service-status-row"><span class="status ${s.status}">${s.statusText}</span></div><div class="service-grid"><div class="meta"><div class="label">Услуга</div>${s.service}</div><div class="meta"><div class="label">Кем создан</div>${s.creator}<br><b class="heading-regular">${s.company}</b><br><span class="label">${s.created}</span></div><div class="meta"><div class="label">Проживание</div><b class="heading-regular">${s.stay}</b></div>${details(s)}<div class="price heading-regular">${s.price}<div class="points">${icon('coins')}${s.points}</div><small>${s.tax}<br>${s.benefit}</small>${voucher(s)}</div></div></div>`}
function render(list=orders){const empty=`<article class="empty-state"><img src="assets/empty-search.png" alt=""><div class="empty-state__text"><h2>Нет подходящих вариантов</h2><p>Нет заказов с выбранными<br>вами фильтрами</p></div><button id="emptyReset" class="empty-state__button" type="button">Сбросить фильтры</button></article>`;document.querySelector('#orders').innerHTML=list.length?list.map(o=>`<article class="order${o.id==='87654321'?' order--clickable':''}"${o.id==='87654321'?` data-href="order.html?id=${o.id}" role="link" tabindex="0"`:''}><h2>Заказ ${o.id}</h2>${o.services.map(service).join('')}</article>`).join(''):empty;document.querySelector('.pagination').classList.toggle('is-hidden',!list.length)}
render();
const filters=document.querySelector('.filters'),search=document.querySelector('#orderSearch'),guestSearch=document.querySelector('#guestSearch'),hotelSearch=document.querySelector('#hotelSearch'),apply=document.querySelector('#applyFilters'),resetFilters=document.querySelector('#resetFilters');
filters.addEventListener('input',()=>apply.disabled=false);
const creatorSearch=document.querySelector('#creatorSearch'),creatorSuggestions=document.querySelector('#creatorSuggestions'),creatorChip=document.querySelector('#creatorChip'),removeCreatorChip=document.querySelector('#removeCreatorChip');
let selectedCreator='';
function closeCreatorSuggestions(){creatorSuggestions.hidden=true;creatorSearch.setAttribute('aria-expanded','false');creatorSuggestions.querySelectorAll('button').forEach(option=>option.classList.remove('is-active'))}
function updateCreatorSuggestions(){const show=creatorSearch.value.trim().toLowerCase().startsWith('смирн');creatorSuggestions.hidden=!show;creatorSearch.setAttribute('aria-expanded',String(show));if(!show)creatorSuggestions.querySelectorAll('button').forEach(option=>option.classList.remove('is-active'))}
creatorSearch.addEventListener('input',updateCreatorSuggestions);
creatorSearch.addEventListener('focus',updateCreatorSuggestions);
creatorSuggestions.addEventListener('click',e=>{const option=e.target.closest('[role="option"]');if(!option)return;const isAnton=option.textContent.startsWith('Смирный Антон');selectedCreator=isAnton?'anton-smirny':'';creatorChip.hidden=!isAnton;creatorSearch.placeholder=isAnton?'Добавить еще':'Имя и фамилия';creatorSearch.value=isAnton?'':option.textContent.split(' · ')[0];creatorSearch.dispatchEvent(new Event('input',{bubbles:true}));closeCreatorSuggestions()});
removeCreatorChip.addEventListener('click',()=>{selectedCreator='';creatorChip.hidden=true;creatorSearch.value='';creatorSearch.placeholder='Имя и фамилия';creatorSearch.focus();creatorSearch.dispatchEvent(new Event('input',{bubbles:true}))});
creatorSearch.addEventListener('keydown',e=>{if(creatorSuggestions.hidden)return;const options=[...creatorSuggestions.querySelectorAll('[role="option"]')],active=creatorSuggestions.querySelector('.is-active');let index=options.indexOf(active);if(e.key==='ArrowDown'){e.preventDefault();index=(index+1)%options.length}else if(e.key==='ArrowUp'){e.preventDefault();index=(index-1+options.length)%options.length}else if(e.key==='Enter'&&active){e.preventDefault();active.click();return}else if(e.key==='Escape'){closeCreatorSuggestions();return}else{return}options.forEach((option,i)=>option.classList.toggle('is-active',i===index));options[index].scrollIntoView({block:'nearest'})});
document.addEventListener('click',e=>{if(!e.target.closest('.creator-suggest'))closeCreatorSuggestions()});
apply.addEventListener('click',()=>{const q=search.value.trim().toLowerCase(),guest=guestSearch.value.trim().toLowerCase(),hotel=hotelSearch.value.trim().toLowerCase(),creator=creatorSearch.value.trim().toLowerCase(),company=filters.querySelector('input[name="company"]:checked')?.value.toLowerCase()||'';const statuses=[...filters.querySelectorAll('input[type="checkbox"]:checked')].map(input=>input.value);const result=orders.filter(o=>{const orderNumberMatches=!q||o.id.toLowerCase().includes(q);return o.services.some(s=>(orderNumberMatches||s.service.toLowerCase().includes(q))&&(!guest||s.guests.toLowerCase().includes(guest))&&(!hotel||(s.hotel+' '+s.address).toLowerCase().includes(hotel))&&(!creator||s.creator.toLowerCase().includes(creator))&&(!selectedCreator||(s.creator==='Смирный Антон'&&s.company.includes('АОН.РУ')))&&(!statuses.length||statuses.includes(s.status))&&(!company||s.contractor.toLowerCase()===company))});render(result);apply.disabled=true;resetFilters.hidden=false;toast(`Найдено заказов: ${result.length}`)});
function resetAllFilters(){filters.querySelectorAll('input').forEach(input=>{if(input.type==='checkbox'||input.type==='radio')input.checked=false;else input.value=''});selectedCreator='';creatorChip.hidden=true;creatorSearch.placeholder='Имя и фамилия';closeCreatorSuggestions();filters.querySelectorAll('.date-field').forEach(field=>{delete field.dataset.start;delete field.dataset.end});render();apply.disabled=true;resetFilters.hidden=true;toast('Фильтры сброшены')}
resetFilters.addEventListener('click',resetAllFilters);
document.querySelector('#orders').addEventListener('click',e=>{if(e.target.closest('#emptyReset'))resetAllFilters();const voucherButton=e.target.closest('.voucher__button');if(voucherButton){const voucherRoot=voucherButton.closest('.voucher'),open=voucherRoot.classList.toggle('is-open');document.querySelectorAll('.voucher.is-open').forEach(item=>{if(item!==voucherRoot){item.classList.remove('is-open');item.querySelector('.voucher__button').setAttribute('aria-expanded','false')}});voucherButton.setAttribute('aria-expanded',String(open));return}if(e.target.closest('.voucher__download')){const voucherRoot=e.target.closest('.voucher');toast('Ваучер скачан');voucherRoot.classList.remove('is-open');voucherRoot.querySelector('.voucher__button').setAttribute('aria-expanded','false');return}const card=e.target.closest('.order--clickable[data-href]');if(card&&!e.target.closest('button,input,a'))location.href=card.dataset.href});
document.querySelector('#orders').addEventListener('keydown',e=>{const card=e.target.closest('.order--clickable[data-href]');if(card&&(e.key==='Enter'||e.key===' ')){e.preventDefault();location.href=card.dataset.href}});
document.addEventListener('click',e=>{if(!e.target.closest('.voucher'))document.querySelectorAll('.voucher.is-open').forEach(item=>{item.classList.remove('is-open');item.querySelector('.voucher__button').setAttribute('aria-expanded','false')})});
const sortBtn=document.querySelector('#sortBtn'),sortMenu=document.querySelector('#sortMenu');
sortBtn.addEventListener('click',()=>{periodMenu.classList.remove('open');periodBtn.setAttribute('aria-expanded','false');const open=sortMenu.classList.toggle('open');sortBtn.setAttribute('aria-expanded',String(open))});
sortMenu.addEventListener('click',e=>{const option=e.target.closest('[data-sort]');if(!option)return;sortMenu.querySelectorAll('[data-sort]').forEach(item=>item.classList.toggle('selected',item===option));sortBtn.querySelector('.sort-label').textContent=option.textContent;sortMenu.classList.remove('open');sortBtn.setAttribute('aria-expanded','false');if(option.dataset.sort==='number')orders.sort((a,b)=>a.id.localeCompare(b.id));else orders.sort((a,b)=>a.services[0].created.localeCompare(b.services[0].created));render();toast(`Сортировка: ${option.textContent}`)});
const periodBtn=document.querySelector('#periodBtn'), periodMenu=document.querySelector('#periodMenu');
periodBtn.addEventListener('click',()=>{sortMenu.classList.remove('open');sortBtn.setAttribute('aria-expanded','false');const open=periodMenu.classList.toggle('open');periodBtn.setAttribute('aria-expanded',String(open))});
periodMenu.addEventListener('click',e=>{const option=e.target.closest('[data-value]');if(!option)return;periodMenu.querySelectorAll('[data-value]').forEach(item=>item.classList.toggle('selected',item===option));periodBtn.querySelector('.period-label').textContent=option.dataset.value;periodMenu.classList.remove('open');periodBtn.setAttribute('aria-expanded','false');toast(`Период: ${option.dataset.value}`)});
document.addEventListener('click',e=>{if(!e.target.closest('.dropdown')){periodMenu.classList.remove('open');periodBtn.setAttribute('aria-expanded','false');sortMenu.classList.remove('open');sortBtn.setAttribute('aria-expanded','false')}});
document.querySelector('#exportBtn').addEventListener('click',()=>toast('Демо: подготовка Excel-файла'));

const pageSizeBtn=document.querySelector('#pageSizeBtn'),pageSizeMenu=document.querySelector('#pageSizeMenu');
pageSizeBtn.addEventListener('click',()=>{const open=pageSizeMenu.classList.toggle('open');pageSizeBtn.setAttribute('aria-expanded',String(open))});
pageSizeMenu.addEventListener('click',e=>{const option=e.target.closest('[data-size]');if(!option)return;pageSizeMenu.querySelectorAll('[data-size]').forEach(item=>item.classList.toggle('selected',item===option));pageSizeBtn.querySelector('.page-size-label').textContent=option.textContent;pageSizeMenu.classList.remove('open');pageSizeBtn.setAttribute('aria-expanded','false');toast(`По ${option.dataset.size} заказов на странице`)});
document.addEventListener('click',e=>{if(!e.target.closest('.page-size-dropdown')){pageSizeMenu.classList.remove('open');pageSizeBtn.setAttribute('aria-expanded','false')}});
function toast(text){const el=document.querySelector('#toast');el.textContent=text;el.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('show'),1800)}

const calendarPopover=document.querySelector('#calendarPopover');
let activeDateInput=null,activeDateField=null;
const monthNames=['Январь','Февраль','Март','Апрель','Май','Июнь','Июль','Август','Сентябрь','Октябрь','Ноябрь','Декабрь'];
const isoDate=(year,month,day)=>`${year}-${String(month+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`;
const displayDate=iso=>{const [year,month,day]=iso.split('-');return `${day}.${month}.${year}`};
function setDateValue(){const start=activeDateField?.dataset.start||'',end=activeDateField?.dataset.end||'';if(!activeDateInput)return;activeDateInput.value=!start?'':(!end||start===end?displayDate(start):`${displayDate(start)} — ${displayDate(end)}`);activeDateInput.dispatchEvent(new Event('input',{bubbles:true}))}
function closeCalendar(){calendarPopover.hidden=true;activeDateField?.classList.remove('is-open')}
function drawCalendar(year=2026,month=7){
  const first=(new Date(year,month,1).getDay()+6)%7,days=new Date(year,month+1,0).getDate(),start=activeDateField?.dataset.start||'',end=activeDateField?.dataset.end||'';
  const dates=Array.from({length:days},(_,i)=>{const day=i+1,iso=isoDate(year,month,day),isStart=iso===start,isEnd=iso===end,isWeekend=(first+i)%7>=5,classes=[isStart?'range-start':'',isEnd?'range-end':'',isWeekend?'weekend':''].filter(Boolean).join(' ');return `<button type="button" data-day="${day}" class="${classes}" aria-label="${day} ${monthNames[month].toLowerCase()} ${year}" aria-pressed="${isStart||isEnd}"><span>${day}</span></button>`}).join('');
  const months=monthNames.map((name,index)=>`<button type="button" data-month="${index}" class="${index===month?'selected':''}">${name}</button>`).join('');
  calendarPopover.innerHTML=`<div class="calendar-picker"><div class="calendar-months" aria-label="Месяц">${months}</div><div class="calendar-main"><div class="calendar-week"><span>пн</span><span>вт</span><span>ср</span><span>чт</span><span>пт</span><span class="weekend">сб</span><span class="weekend">вс</span></div><div class="calendar-scroll"><section><b>${monthNames[month]} ${year}</b><div class="calendar-days">${'<i></i>'.repeat(first)}${dates}</div></section></div></div></div>`;
  calendarPopover.dataset.year=year;calendarPopover.dataset.month=month;
}
document.querySelectorAll('.date-field').forEach(field=>field.addEventListener('click',()=>{activeDateField?.classList.remove('is-open');activeDateField=field;activeDateField.classList.add('is-open');activeDateInput=field.querySelector('.date-input');const rect=field.getBoundingClientRect(),visibleIso=field.dataset.start;let year=2026,month=7;if(visibleIso){const parts=visibleIso.split('-');year=+parts[0];month=+parts[1]-1}drawCalendar(year,month);calendarPopover.hidden=false;const popupWidth=Math.min(570,window.innerWidth-24);calendarPopover.style.width=`${popupWidth}px`;calendarPopover.style.left=`${Math.max(12,Math.min(rect.left,window.innerWidth-popupWidth-12))}px`;calendarPopover.style.top=`${rect.bottom+8+window.scrollY}px`;activeDateInput.focus()}));
calendarPopover.addEventListener('click',e=>{
  e.stopPropagation();
  const shift=e.target.closest('[data-shift]');if(shift){let year=+calendarPopover.dataset.year,month=+calendarPopover.dataset.month+ +shift.dataset.shift;if(month<0){month=11;year--}if(month>11){month=0;year++}drawCalendar(year,month);return}
  const monthButton=e.target.closest('button[data-month]');if(monthButton){drawCalendar(+calendarPopover.dataset.year,+monthButton.dataset.month);return}
  const day=e.target.closest('[data-day]');if(!day||!activeDateInput||!activeDateField)return;const selected=isoDate(+calendarPopover.dataset.year,+calendarPopover.dataset.month,+day.dataset.day),start=activeDateField.dataset.start,end=activeDateField.dataset.end;if(!start||end){activeDateField.dataset.start=selected;delete activeDateField.dataset.end}else if(selected<start){activeDateField.dataset.start=selected;activeDateField.dataset.end=start}else{activeDateField.dataset.end=selected}setDateValue();drawCalendar(+calendarPopover.dataset.year,+calendarPopover.dataset.month)
});
document.addEventListener('click',e=>{if(!e.target.closest('.date-field')&&!e.target.closest('#calendarPopover'))closeCalendar()});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!calendarPopover.hidden)closeCalendar()});
