const roomCount=document.querySelector('#roomCount');
const priceRoomCount=document.querySelector('#priceRoomCount');
const totalPrice=document.querySelector('#totalPrice');
const bookingParams=new URLSearchParams(window.location.search);
const guestWord=value=>{const mod10=value%10,mod100=value%100;return mod10===1&&mod100!==11?'гость':mod10>=2&&mod10<=4&&(mod100<12||mod100>14)?'гостя':'гостей'};
let bookingAdults=Math.max(1,Number(bookingParams.get('adults'))||1);
let bookingChildren=Math.max(0,Number(bookingParams.get('children'))||0);
let bookingRooms=Math.max(1,Number(bookingParams.get('rooms'))||1);
let bookingExtraAdults=Math.max(0,Number(bookingParams.get('extraAdults'))||0);
let bookingExtraChildren=Math.max(0,Number(bookingParams.get('extraChildren'))||0);
let bookingGuestTotal=bookingAdults+bookingChildren;
let bookingMainGuests=Math.max(1,bookingGuestTotal-bookingExtraAdults-bookingExtraChildren);
let incomingPrice=Number((bookingParams.get('price')||'40 000').replace(/[^\d]/g,''))||40000;
let extraStayPrice=0;
const serviceFee=904.92;
const formatWhole=value=>`${value.toLocaleString('ru-RU')} ₽`;
const updateBookingTotal=()=>{const count=Number(roomCount.textContent);priceRoomCount.textContent=String(count);totalPrice.textContent=`${((incomingPrice+extraStayPrice+serviceFee)*count).toLocaleString('ru-RU',{minimumFractionDigits:2,maximumFractionDigits:2})} ₽`};
const hotelName=bookingParams.get('hotel');
const hotelAddress=bookingParams.get('address');
if(hotelName){document.querySelector('.booking-title h1').textContent=hotelName;document.querySelector('.breadcrumbs a:nth-of-type(2)').textContent=hotelName;document.title=`Новый заказ — ${hotelName}`}
if(hotelAddress)document.querySelector('.booking-title>p').textContent=hotelAddress;
roomCount.textContent=String(bookingRooms);
const stayGuests=document.querySelector('.stay-summary>div:nth-child(3)');
const syncBookingGuests=()=>{bookingGuestTotal=bookingMainGuests+bookingExtraAdults+bookingExtraChildren;bookingAdults=bookingMainGuests+bookingExtraAdults;bookingChildren=bookingExtraChildren;stayGuests.querySelector('b').textContent=`${bookingGuestTotal} ${guestWord(bookingGuestTotal)}`;stayGuests.querySelector('span').textContent=bookingExtraAdults||bookingExtraChildren?`${bookingMainGuests} на основных · ${bookingExtraAdults+bookingExtraChildren} на доп. кроватях`:'на основных кроватях';document.querySelector('.booking-details dd:first-of-type b').textContent=bookingRooms>1?`Всего ${bookingGuestTotal} ${guestWord(bookingGuestTotal)} в ${bookingRooms} номерах`:`Всего ${bookingGuestTotal} ${guestWord(bookingGuestTotal)} в номере`;bookingParams.set('adults',String(bookingAdults));bookingParams.set('children',String(bookingChildren));bookingParams.set('rooms',String(bookingRooms));bookingParams.set('extraAdults',String(bookingExtraAdults));bookingParams.set('extraChildren',String(bookingExtraChildren));history.replaceState(null,'',`${location.pathname}?${bookingParams}`)};
syncBookingGuests();
const initialDrawerCounts=document.querySelectorAll('#bookingDetailsDrawer [data-count]');
if(initialDrawerCounts.length){initialDrawerCounts[0].textContent=String(bookingMainGuests);initialDrawerCounts[1].textContent=String(bookingExtraAdults);initialDrawerCounts[2].textContent=String(bookingExtraChildren);document.querySelector('#bookingDetailsDrawer .drawer-guests__trigger span').textContent=`${bookingGuestTotal} ${guestWord(bookingGuestTotal)}`}
const bookingPriceLines=document.querySelectorAll('.price-card .price-line');
bookingPriceLines[1].querySelector('b').textContent=formatWhole(incomingPrice);
bookingPriceLines[2].querySelector('b').textContent=formatWhole(incomingPrice);
updateBookingTotal();
document.querySelectorAll('[data-step]').forEach(button=>button.addEventListener('click',()=>{
  const next=Math.max(1,Math.min(4,Number(roomCount.textContent)+Number(button.dataset.step)));
  bookingRooms=next;roomCount.textContent=String(next);syncBookingGuests();updateBookingTotal();
}));
const extraStay=document.querySelector('#extraStay');
const extraStayOptions={checkin:[['standard','Стандартный заезд 15:00',''],['instant','Ранний заезд 1:00','2 493 ₽'],['request','Ранний заезд 2:00','2 493 ₽'],['request','Ранний заезд 3:00','2 493 ₽'],['instant','Ранний заезд 4:00','2 493 ₽'],['request','Ранний заезд 5:00','2 493 ₽']],checkout:[['standard','Стандартный выезд 12:00',''],['instant','Поздний выезд 13:00','12 493 ₽'],['request','Поздний выезд 14:00','12 493 ₽'],['request','Поздний выезд 15:00','12 493 ₽'],['instant','Поздний выезд 16:00','12 493 ₽'],['request','Поздний выезд 17:00','12 493 ₽']]};
const setExtraStayDropdown=(dropdown,value)=>{const option=extraStayOptions[dropdown.dataset.extraStay].find(item=>item[0]===value)||extraStayOptions[dropdown.dataset.extraStay][0];dropdown.dataset.value=option[0];dropdown.dataset.extraPrice=option[2].replace(/[^\d]/g,'');const label=dropdown.querySelector(':scope > button > span');label.innerHTML=option[2]?`<span>${option[1].replace(' · под запрос','')}</span><b>${option[2]}</b>`:option[1]};
if(extraStay)extraStay.querySelectorAll('[data-extra-stay]').forEach(dropdown=>{dropdown.querySelector('.booking-dropdown__menu').innerHTML=extraStayOptions[dropdown.dataset.extraStay].map(([value,label,price],index)=>`<button type="button" role="option" aria-selected="${index===0}" data-value="${value}" data-label="${label}"${price?` data-price="${price}"`:''}><span>${label}</span>${price?`<b>${price}</b>`:''}</button>`).join('')});
const updateExtraStay=()=>{if(!extraStay)return;const checkin=extraStay.querySelector('[data-extra-stay="checkin"]');const checkout=extraStay.querySelector('[data-extra-stay="checkout"]');const checkinValue=checkin.dataset.value||'standard';const checkoutValue=checkout.dataset.value||'standard';const details=extraStay.querySelector('.extra-stay__details');const checkinDetail=extraStay.querySelector('[data-extra-detail="checkin"]');const checkoutDetail=extraStay.querySelector('[data-extra-detail="checkout"]');const instant=extraStay.querySelector('.extra-stay__instant');checkinDetail.hidden=checkinValue!=='request';checkoutDetail.hidden=checkoutValue!=='request';instant.hidden=!(checkinValue==='instant'&&checkoutValue==='instant');details.hidden=checkinDetail.hidden&&checkoutDetail.hidden&&instant.hidden;extraStay.classList.toggle('is-unavailable',checkinValue==='unavailable'&&checkoutValue==='unavailable');extraStayPrice=Number(checkin.dataset.extraPrice||0)+Number(checkout.dataset.extraPrice||0);updateBookingTotal()};
document.querySelectorAll('.booking-dropdown').forEach(dropdown=>{
  const trigger=dropdown.querySelector(':scope > button');
  const menu=dropdown.querySelector('.booking-dropdown__menu');
  const close=()=>{menu.hidden=true;dropdown.classList.remove('is-open');trigger.setAttribute('aria-expanded','false')};
  trigger.addEventListener('click',event=>{
    event.stopPropagation();
    document.querySelectorAll('.booking-dropdown.is-open').forEach(item=>{if(item!==dropdown){item.classList.remove('is-open');item.querySelector('.booking-dropdown__menu').hidden=true;item.querySelector(':scope > button').setAttribute('aria-expanded','false')}});
    const opening=menu.hidden;menu.hidden=!opening;dropdown.classList.toggle('is-open',opening);trigger.setAttribute('aria-expanded',String(opening));
  });
  menu.addEventListener('click',event=>{const option=event.target.closest('[role="option"]');if(!option)return;const label=option.dataset.label||option.textContent;if(option.dataset.price){trigger.querySelector('span').innerHTML=`<span>${label.replace(' · под запрос','')}</span><b>${option.dataset.price}</b>`}else{trigger.querySelector('span').textContent=label}if(dropdown.dataset.extraStay){dropdown.dataset.value=option.dataset.value||'standard';dropdown.dataset.extraPrice=option.dataset.price?option.dataset.price.replace(/[^\d]/g,''):0;if(option.dataset.value==='hourly'||option.dataset.value==='unavailable'){const other=extraStay.querySelector(`[data-extra-stay="${dropdown.dataset.extraStay==='checkin'?'checkout':'checkin'}"]`);setExtraStayDropdown(other,option.dataset.value)}}menu.querySelectorAll('[role="option"]').forEach(item=>item.setAttribute('aria-selected',String(item===option)));updateExtraStay();close()});
  dropdown._close=close;
});
document.addEventListener('click',()=>document.querySelectorAll('.booking-dropdown.is-open').forEach(dropdown=>dropdown._close()));
document.querySelector('#bookButton').addEventListener('click',()=>{const orderParams=new URLSearchParams({id:'87654321',hotel:hotelName||document.querySelector('.booking-title h1').textContent.trim(),address:hotelAddress||document.querySelector('.booking-title>p').textContent.trim(),price:String(incomingPrice),adults:String(bookingAdults),children:String(bookingChildren),rooms:String(bookingRooms)});window.location.href=`order.html?${orderParams}`});
document.querySelectorAll('.ref-field').forEach(field=>{const input=field.querySelector('input');const clear=field.querySelector('button');const update=()=>{const filled=Boolean(input.value);field.classList.toggle('has-value',filled);clear.hidden=!filled};input.addEventListener('input',update);clear.addEventListener('click',()=>{input.value='';update();input.focus()});update()});
const conditionsModal=document.querySelector('#conditionsModal');
const showAllConditions=document.querySelector('#showAllConditions');
const closeConditionsModal=()=>{conditionsModal.hidden=true;document.body.classList.remove('modal-open');showAllConditions.focus()};
showAllConditions.addEventListener('click',()=>{conditionsModal.hidden=false;document.body.classList.add('modal-open');conditionsModal.querySelector('.conditions-modal__close').focus()});
conditionsModal.addEventListener('click',event=>{if(event.target.closest('.conditions-modal__close')){event.preventDefault();event.stopPropagation();closeConditionsModal()}});
conditionsModal.querySelector('.conditions-modal__backdrop').addEventListener('click',closeConditionsModal);
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!conditionsModal.hidden)closeConditionsModal()});

const detailsDrawer=document.querySelector('#bookingDetailsDrawer');
const detailsDrawerClose=()=>{detailsDrawer.hidden=true;document.body.classList.remove('drawer-open');document.querySelector('#editBookingDetails').focus()};
const detailsDrawerOpen=()=>{detailsDrawer.hidden=false;document.body.classList.add('drawer-open');detailsDrawer.querySelector('.booking-drawer-close').focus()};
document.querySelector('#editBookingDetails').addEventListener('click',detailsDrawerOpen);
detailsDrawer.querySelector('.booking-drawer-close').addEventListener('click',detailsDrawerClose);
detailsDrawer.querySelector('.booking-drawer-backdrop').addEventListener('click',detailsDrawerClose);
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!detailsDrawer.hidden)detailsDrawerClose()});

const guestsTrigger=detailsDrawer.querySelector('.drawer-guests__trigger');
const guestsMenu=detailsDrawer.querySelector('.drawer-guests__menu');
const drawerDateButton=detailsDrawer.querySelector('#drawerDateButton');
const drawerDateLabel=detailsDrawer.querySelector('#drawerDateLabel');
const drawerCalendar=detailsDrawer.querySelector('#drawerCalendar');
const calendarMonths=[['Июль',6,2026,'июля'],['Август',7,2026,'августа'],['Сентябрь',8,2026,'сентября'],['Октябрь',9,2026,'октября'],['Ноябрь',10,2026,'ноября'],['Декабрь',11,2026,'декабря'],['Январь 2027',0,2027,'января'],['Февраль',1,2027,'февраля'],['Март',2,2027,'марта'],['Апрель',3,2027,'апреля'],['Май',4,2027,'мая'],['Июнь',5,2027,'июня']];
let calendarMonth=0;
let rangeStart=new Date(2026,6,12);
let rangeEnd=new Date(2026,6,14);
const sameDay=(a,b)=>a&&b&&a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth()&&a.getDate()===b.getDate();
const renderDrawerCalendar=()=>{const [name,month,year]=calendarMonths[calendarMonth];const first=(new Date(year,month,1).getDay()+6)%7;const length=new Date(year,month+1,0).getDate();const days=Array.from({length},(_,index)=>{const date=new Date(year,month,index+1);const weekend=(first+index)%7>=5;const inRange=rangeStart&&rangeEnd&&date>rangeStart&&date<rangeEnd;return `<button type="button" data-date="${year}-${String(month+1).padStart(2,'0')}-${String(index+1).padStart(2,'0')}" class="${[weekend?'weekend':'',sameDay(date,rangeStart)?'range-start':'',sameDay(date,rangeEnd)?'range-end':'',inRange?'in-range':''].filter(Boolean).join(' ')}"><span>${index+1}</span></button>`}).join('');drawerCalendar.innerHTML=`<div class="calendar-picker"><div class="calendar-months">${calendarMonths.map((item,index)=>`<button type="button" data-month="${index}" class="${index===calendarMonth?'selected':''}">${item[0]}</button>`).join('')}</div><div class="calendar-main"><div class="calendar-week"><span>пн</span><span>вт</span><span>ср</span><span>чт</span><span>пт</span><span class="weekend">сб</span><span class="weekend">вс</span></div><div class="calendar-scroll"><section><b>${name} ${year}</b><div class="calendar-days">${'<i></i>'.repeat(first)}${days}</div></section></div></div></div>`};
const closeGuests=()=>{guestsMenu.hidden=true;guestsTrigger.setAttribute('aria-expanded','false')};
const closeCalendar=()=>{drawerCalendar.hidden=true;drawerDateButton.setAttribute('aria-expanded','false')};
renderDrawerCalendar();
drawerDateButton.addEventListener('click',()=>{const open=drawerCalendar.hidden;closeGuests();drawerCalendar.hidden=!open;drawerDateButton.setAttribute('aria-expanded',String(open))});
drawerCalendar.addEventListener('click',event=>{const monthButton=event.target.closest('[data-month]');if(monthButton){calendarMonth=Number(monthButton.dataset.month);renderDrawerCalendar();return}const dayButton=event.target.closest('[data-date]');if(!dayButton)return;const picked=new Date(`${dayButton.dataset.date}T12:00:00`);if(!rangeStart||rangeEnd||picked<rangeStart){rangeStart=picked;rangeEnd=null}else{rangeEnd=picked;const nights=Math.round((rangeEnd-rangeStart)/86400000);const weekday=['вс','пн','вт','ср','чт','пт','сб'];const startMonth=calendarMonths.find(item=>item[1]===rangeStart.getMonth()&&item[2]===rangeStart.getFullYear());const endMonth=calendarMonths.find(item=>item[1]===rangeEnd.getMonth()&&item[2]===rangeEnd.getFullYear());drawerDateLabel.innerHTML=`${rangeStart.getDate()} ${startMonth[3]} ${rangeStart.getFullYear()} <i>${weekday[rangeStart.getDay()]}</i> – ${rangeEnd.getDate()} ${endMonth[3]} ${rangeEnd.getFullYear()} <i>${weekday[rangeEnd.getDay()]}</i> <i>· ${nights} ночи</i>`;closeCalendar()}renderDrawerCalendar()});
guestsTrigger.addEventListener('click',()=>{const open=guestsMenu.hidden;closeCalendar();guestsMenu.hidden=!open;guestsTrigger.setAttribute('aria-expanded',String(open))});
document.addEventListener('pointerdown',event=>{if(!event.target.closest('.drawer-guests'))closeGuests();if(!event.target.closest('.drawer-date'))closeCalendar()},true);
detailsDrawer.querySelectorAll('[data-drawer-step]').forEach(button=>button.addEventListener('click',()=>{const value=button.parentElement.querySelector('[data-count]');const minimum=value.dataset.count==='main'?1:0;value.textContent=String(Math.max(minimum,Number(value.textContent)+Number(button.dataset.drawerStep)));bookingMainGuests=Number(initialDrawerCounts[0].textContent);bookingExtraAdults=Number(initialDrawerCounts[1].textContent);bookingExtraChildren=Number(initialDrawerCounts[2].textContent);syncBookingGuests();guestsTrigger.querySelector('span').textContent=`${bookingGuestTotal} ${guestWord(bookingGuestTotal)}`;detailsDrawer.querySelectorAll('[data-drawer-step="-1"]').forEach((minus,index)=>minus.disabled=Number(initialDrawerCounts[index].textContent)<=(index===0?1:0));mealGuestCount.textContent=String(bookingGuestTotal);updateMealGuestControls();updateMealTotal()}));
detailsDrawer.querySelectorAll('.drawer-offer>button').forEach(button=>{const availability=document.createElement('small');availability.className=`drawer-offer__availability${button.classList.contains('dark')?' is-request':''}`;availability.textContent=button.classList.contains('dark')?'Под запрос':'В наличии: 4';button.after(availability)});
detailsDrawer.querySelectorAll('.drawer-offer>button').forEach(button=>button.addEventListener('click',()=>{detailsDrawer.querySelectorAll('.drawer-offer>button').forEach(item=>{item.disabled=false;item.classList.remove('dark');item.textContent='Выбрать'});button.disabled=true;button.textContent='Выбран';incomingPrice=Number(button.parentElement.querySelector('.drawer-offer__price strong').textContent.replace(/[^\d]/g,''));bookingPriceLines[1].querySelector('b').textContent=formatWhole(incomingPrice);bookingPriceLines[2].querySelector('b').textContent=formatWhole(incomingPrice);updateBookingTotal()}));

const mealDrawer=document.querySelector('#mealDrawer');
const addMealButton=document.querySelector('#addMeal');
const mealGuestCount=document.querySelector('#mealGuestCount');
const mealCalendar=document.querySelector('#mealCalendar');
const mealDateCaption=document.querySelector('#mealDateCaption');
const mealCalculation=document.querySelector('#mealCalculation');
const mealTotal=document.querySelector('#mealTotal');
const addedMeals=document.querySelector('#addedMeals');
let mealPrice=2500;
let mealName='Полупансион (завтрак и ужин)';
let mealPeriod='all';
let mealSelectedDays=new Set([20]);
const formatMealDates=days=>{const sorted=[...days].sort((a,b)=>a-b);if(!sorted.length)return'';const ranges=[];let start=sorted[0],end=sorted[0];for(let index=1;index<=sorted.length;index+=1){const day=sorted[index];if(day===end+1){end=day;continue}ranges.push(start===end?`${start}–${end+1}`:`${start}–${end+1}`);start=day;end=day}return`${ranges.join(', ')} дек 2026`};
mealGuestCount.textContent=String(bookingGuestTotal);
const mealGuestWord=count=>count===1?'гость':count>1&&count<5?'гостя':'гостей';
const updateMealGuestControls=()=>{const count=Number(mealGuestCount.textContent);mealDrawer.querySelector('[data-meal-step="-1"]').disabled=count<=1;mealDrawer.querySelector('[data-meal-step="1"]').disabled=count>=8};
const updateMealTotal=()=>{const guests=Number(mealGuestCount.textContent);const days=mealPeriod==='days'?Math.max(1,mealSelectedDays.size):1;const total=mealPrice*guests*days;mealCalculation.textContent=`${formatWhole(mealPrice)} · ${guests} ${mealGuestWord(guests)}${mealPeriod==='days'?` · ${days} ${days===1?'день':'дня'}`:''}`;mealTotal.textContent=formatWhole(total)};
const renderMealCalendar=()=>{const first=4;const december=Array.from({length:31},(_,index)=>{const day=index+1;const weekend=(first+index)%7>=5;const outside=day<20||day>24;return `<button type="button" data-meal-day="${day}" class="${[weekend?'weekend':'',outside?'is-outside':'',mealSelectedDays.has(day)?'is-selected':''].filter(Boolean).join(' ')}"><span>${day}</span></button>`}).join('');mealCalendar.innerHTML=`<div class="meal-calendar__months"><button type="button">Июль</button><button type="button">Август</button><button type="button">Сентябрь</button><button type="button">Октябрь</button><button type="button">Ноябрь</button><button type="button" class="is-active">Декабрь</button><button type="button">Январь 2027</button><button type="button">Февраль</button><button type="button">Март</button><button type="button">Апрель</button><button type="button">Май</button><button type="button">Июнь</button></div><div class="meal-calendar__main"><div class="meal-calendar__week"><span>пн</span><span>вт</span><span>ср</span><span>чт</span><span>пт</span><span class="weekend">сб</span><span class="weekend">вс</span></div><h4>Декабрь</h4><div class="meal-calendar__days">${'<i></i>'.repeat(first)}${december}</div><h4>Январь 2027</h4><div class="meal-calendar__days"><i></i><i></i><i></i><i></i><button type="button" class="is-outside">1</button><button type="button" class="is-outside weekend">2</button><button type="button" class="is-outside weekend">3</button></div></div>`};
const setMealPeriod=period=>{mealPeriod=period;mealDrawer.querySelectorAll('[data-meal-period]').forEach(button=>{const active=button.dataset.mealPeriod===period;button.classList.toggle('is-active',active);button.setAttribute('aria-selected',String(active))});const selected=period==='days';mealGuestCount.textContent=String(bookingGuestTotal);mealCalendar.hidden=!selected;mealDateCaption.textContent=selected?formatMealDates(mealSelectedDays):'20–24 дек 2026';updateMealGuestControls();updateMealTotal()};
const closeMealDrawer=()=>{mealDrawer.hidden=true;document.body.classList.remove('drawer-open');addMealButton.focus()};
const openMealDrawer=()=>{mealDrawer.hidden=false;document.body.classList.add('drawer-open');mealDrawer.querySelector('.meal-drawer__close').focus()};
renderMealCalendar();
updateMealGuestControls();
updateMealTotal();
addMealButton.addEventListener('click',openMealDrawer);
mealDrawer.querySelector('.meal-drawer__close').addEventListener('click',closeMealDrawer);
mealDrawer.querySelector('.meal-drawer__backdrop').addEventListener('click',closeMealDrawer);
mealDrawer.querySelector('[data-meal-cancel]').addEventListener('click',closeMealDrawer);
const mealSelect=mealDrawer.querySelector('.meal-select');
const mealSelectTrigger=mealSelect.querySelector(':scope > button');
const mealSelectMenu=mealSelect.querySelector('.meal-select__menu');
const closeMealSelect=()=>{mealSelectMenu.hidden=true;mealSelect.classList.remove('is-open');mealSelectTrigger.setAttribute('aria-expanded','false')};
mealSelectTrigger.addEventListener('click',event=>{event.stopPropagation();const opening=mealSelectMenu.hidden;mealSelectMenu.hidden=!opening;mealSelect.classList.toggle('is-open',opening);mealSelectTrigger.setAttribute('aria-expanded',String(opening))});
mealSelectMenu.addEventListener('click',event=>{const option=event.target.closest('[data-meal-price]');if(!option)return;mealPrice=Number(option.dataset.mealPrice);mealName=option.dataset.mealName;mealSelectTrigger.querySelector('span').textContent=mealName;mealSelectTrigger.querySelector('b').textContent=formatWhole(mealPrice);mealSelectMenu.querySelectorAll('[role="option"]').forEach(item=>item.setAttribute('aria-selected',String(item===option)));updateMealTotal();closeMealSelect()});
document.addEventListener('pointerdown',event=>{if(!event.target.closest('.meal-select'))closeMealSelect()},true);
mealDrawer.querySelectorAll('[data-meal-period]').forEach(button=>button.addEventListener('click',()=>setMealPeriod(button.dataset.mealPeriod)));
mealDrawer.querySelectorAll('[data-meal-step]').forEach(button=>button.addEventListener('click',()=>{mealGuestCount.textContent=String(Math.max(1,Math.min(8,Number(mealGuestCount.textContent)+Number(button.dataset.mealStep))));updateMealGuestControls();updateMealTotal()}));
mealCalendar.addEventListener('click',event=>{const day=event.target.closest('[data-meal-day]');if(!day||day.classList.contains('is-outside'))return;const value=Number(day.dataset.mealDay);if(mealSelectedDays.has(value)&&mealSelectedDays.size>1)mealSelectedDays.delete(value);else mealSelectedDays.add(value);mealDateCaption.textContent=formatMealDates(mealSelectedDays);renderMealCalendar();updateMealTotal()});
const renderAddedMeal=(name,price,guests,dates,days)=>{const row=document.createElement('article');row.className='food-card__item';row.dataset.mealPrice=String(price);row.dataset.mealDays=String(days);row.innerHTML=`<h3>${name}</h3><div class="food-card__item-row"><div class="food-card__date-control"><button type="button" class="food-card__dates" aria-expanded="false"><img src="assets/calendar.svg" alt="">${dates}</button><div class="food-card__date-tooltip" role="tooltip" hidden>Измените даты, когда<br>необходимо питание</div></div><b class="food-card__unit-price">${formatWhole(price)}</b><span class="food-card__guests-label">гости</span><div class="food-card__counter"><button type="button" data-added-step="-1" aria-label="Уменьшить" ${guests<=1?'disabled':''}>−</button><b data-added-count>${guests}</b><button type="button" data-added-step="1" aria-label="Увеличить">+</button></div><strong data-added-total>${formatWhole(price*guests*days)}</strong><button class="food-card__remove" type="button" aria-label="Удалить питание"><img src="assets/hotel/close-circle-bg-24.svg" alt=""></button></div>`;addedMeals.append(row);addedMeals.hidden=false};
mealDrawer.querySelector('[data-meal-add]').addEventListener('click',()=>{const guests=Number(mealGuestCount.textContent);const days=mealPeriod==='days'?Math.max(1,mealSelectedDays.size):1;const dates=mealPeriod==='days'?formatMealDates(mealSelectedDays):'20–24 дек 2026';renderAddedMeal(mealName,mealPrice,guests,dates,days);closeMealDrawer()});
const closeMealDateTooltips=except=>{addedMeals.querySelectorAll('.food-card__date-tooltip').forEach(tooltip=>{if(tooltip!==except){tooltip.hidden=true;tooltip.previousElementSibling.setAttribute('aria-expanded','false')}})};
addedMeals.addEventListener('click',event=>{const row=event.target.closest('.food-card__item');if(!row)return;const dateButton=event.target.closest('.food-card__dates');if(dateButton){const tooltip=dateButton.nextElementSibling;const opening=tooltip.hidden;closeMealDateTooltips(tooltip);tooltip.hidden=!opening;dateButton.setAttribute('aria-expanded',String(opening));return}if(event.target.closest('.food-card__remove')){row.remove();addedMeals.hidden=!addedMeals.children.length;return}const step=event.target.closest('[data-added-step]');if(!step)return;const countNode=row.querySelector('[data-added-count]');const count=Math.max(1,Math.min(8,Number(countNode.textContent)+Number(step.dataset.addedStep)));countNode.textContent=String(count);row.querySelector('[data-added-step="-1"]').disabled=count<=1;row.querySelector('[data-added-step="1"]').disabled=count>=8;row.querySelector('[data-added-total]').textContent=formatWhole(Number(row.dataset.mealPrice)*Number(row.dataset.mealDays)*count)});
document.addEventListener('pointerdown',event=>{if(!event.target.closest('.food-card__date-control'))closeMealDateTooltips()},true);
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!mealDrawer.hidden)closeMealDrawer()});
