(() => {
  const button=document.querySelector('.profile'); if(!button)return;
  button.id='profileButton'; button.type='button'; button.setAttribute('aria-haspopup','menu'); button.setAttribute('aria-expanded','false');
  let menu=document.querySelector('#profileMenu');
  if(!menu){menu=document.createElement('div');menu.id='profileMenu';menu.className='profile-menu';menu.role='menu';menu.hidden=true;menu.innerHTML=`<button class="profile-menu__close" type="button" aria-label="Закрыть"><img src="assets/profile-close-24.svg" alt=""></button><div class="profile-menu__lead"><div class="profile-menu__avatar"><img src="assets/profile-avatar-80.svg" alt=""></div><strong>Иван Иванов</strong><span>ООО «Ромашка»</span></div><div class="profile-menu__group"><a href="payments.html" role="menuitem" data-profile-item="payments"><img src="assets/profile-calendar-24.svg" alt=""><span>График платежей</span></a><a href="payment-documents.html" role="menuitem" data-profile-item="documents"><img src="assets/profile-document-24.svg" alt=""><span>Платежные документы</span></a><button type="button" role="menuitem"><img src="assets/profile-people-24.svg" alt=""><span>Управление пользователями</span></button><button type="button" role="menuitem"><img src="assets/profile-bill-24.svg" alt=""><span>Покупатель в счете-фактуре</span></button><button type="button" role="menuitem"><img src="assets/profile-document-24.svg" alt=""><span>Настройки документов</span></button><button type="button" role="menuitem"><img src="assets/profile-route-24.svg" alt=""><span>Ценовое предложение</span></button></div><div class="profile-menu__divider"></div><div class="profile-menu__group"><button type="button" role="menuitem"><img src="assets/profile-settings-24.svg" alt=""><span>Настройки</span></button><button type="button" role="menuitem"><img src="assets/profile-language-24.svg" alt=""><span>Язык<small>Русский</small></span></button><button type="button" role="menuitem"><img src="assets/profile-night-24.svg" alt=""><span>Тёмная тема</span></button><button type="button" role="menuitem"><img src="assets/profile-exit-24.svg" alt=""><span>Выйти</span></button></div>`;document.querySelector('.topbar').after(menu)}
  const active=location.pathname.endsWith('/payment-documents.html')?'documents':location.pathname.endsWith('/payments.html')?'payments':document.body.dataset.profileSection; menu.querySelectorAll('[data-profile-item]').forEach(item=>item.classList.toggle('is-active',item.dataset.profileItem===active));
  const close=()=>{menu.hidden=true;button.setAttribute('aria-expanded','false')};
  button.addEventListener('click',e=>{e.stopPropagation();const open=menu.hidden;menu.hidden=!open;button.setAttribute('aria-expanded',String(open))});menu.querySelector('.profile-menu__close').addEventListener('click',close);menu.addEventListener('click',e=>e.stopPropagation());document.addEventListener('click',close);document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});
})();
